version: '3.8'
services:
  s3fs:
    container_name: s3fs
    image: efrecon/s3fs:tm
    restart: on-failure:3
    cap_add:
      - SYS_ADMIN
    security_opt:
      - 'apparmor:unconfined'
    devices:
      - /dev/fuse
    volumes:
      - './bucket:/opt/s3fs/bucket:rshared'
    environment:
      AWS_S3_BUCKET: '${AWS_S3_BUCKET}'
      AWS_S3_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
      AWS_S3_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
      AWS_S3_AUTHFILE: '${AWS_S3_AUTHFILE}'
      AWS_S3_SECRET_ACCESS_KEY_FILE: '${AWS_S3_SECRET_ACCESS_KEY_FILE}'
      AWS_S3_URL: '${AWS_S3_URL}'
      AWS_S3_ENDPOINT: '${AWS_S3_ENDPOINT}'
      AWS_S3_MOUNT: '/opt/s3fs/bucket'
      S3FS_ARGS: '${AWS_S3FS_ARGS}'
      S3FS_DEBUG: 0
      AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
      AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
      AWS_SESSION_TOKEN: '${AWS_SESSION_TOKEN}'
      AWSACCESSKEYID: '${AWS_ACCESS_KEY_ID}'
      AWSSECRETACCESSKEY: '${AWS_SECRET_ACCESS_KEY}'
      AWSSESSIONTOKEN: '${AWS_SESSION_TOKEN}'
      UID: '${UID}'
      GID: '${GID}'
